### ISSUE TITLE
"ENOENT: no such file or directory" with scoped package names

### ISSUE THREAD

**Issue by tristanhoy** [nicojs/node-install-local#1]
A package with the name **<span>@</span>scope/module** will be packed by `npm pack` to **scope-module-version.tgz**.

install-local then triess to look for **%TEMP%/<span>@</span>scope/module-version.tgz**, when `npm pack` has created **%TEMP%/scope-module-version.tgz**.

**Comment by nicojs** [comment]
Thanks for the detailed description. I'll try to fix it tomorrow

**Comment by nicojs** [comment]
Its released in v0.4. Could you verify it works?

**Comment by tristanhoy** [comment]
Working. Thanks!
