### ISSUE TITLE
Problem on concurrent installation of the same package

### ISSUE THREAD

**Issue by Archcry** [nicojs/node-install-local#10]
When trying to install the same package in multiple projects concurrently I get an error because of the fact that it tries to find a file in the `/tmp` directory. This file is removed by the other instance of `install-local` unfortunately.

```
[Error: ENOENT: no such file or directory, unlink '/tmp/stryker-0.24.2.tgz']
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/tmp/stryker-0.24.2.tgz'
```

A good way to counter this issue is by creating a uniquely named folder in `/tmp` in which the `.tgz` is build. This way it will only unlink its own version of the package made.

**Comment by nicojs** [comment]
Released in 0.6.0
