### ISSUE TITLE
Naively following README for npmEnv results in "npm: command not found"

### ISSUE THREAD

**Issue by carlgieringer** [nicojs/node-install-local#13]
I didn't understand from the README that `npmEnv` overwrites the whole environment.  When I passed `{ TEST: 'HI' }` I got the error "npm: command not found" because `PATH` was missing from the `exec`'s environment.  Restoring `PATH` fixed the issue.  I have a PR for updating the README to clarify this behavior.  Thanks for the useful tool!

**Comment by nicojs** [comment]
Closed with #14
