### ISSUE TITLE
This library rocks!

### ISSUE THREAD

**Issue by anodynos** [nicojs/node-install-local#15]
Just wanted to say, this library ROCKS, it's a life saver for local libs & lerna style monorepos:-)

Pitty not so many people know about it and use it :-( 
![image](https://user-images.githubusercontent.com/856453/47260485-7eb82800-d4b4-11e8-9733-a9e2d20ab594.png)

**Comment by nicojs** [comment]
Haha @anodyno thanks for the kind words. Glad to hear this tool is as useful for you. Keep spreading the word! 

I don't personally mind the download stats. It works for us, so anyone it can help besides us is a plus.
