### ISSUE TITLE
Compiled files in .gitignore are ignored

### ISSUE THREAD

**Issue by anodynos** [nicojs/node-install-local#18]
My `./build`folder is in `.gitignore` and because of this not added to the .tgz file, hence local-install fails. 
When I comment out the `.gitignore` entry, it works fine. 

How can we make it ignore `.gitingore` (!) or better specify a non-ignored filespec?

**Comment by nicojs** [comment]
Dear @anodynos this is _exactly why I created `install-local`_. Indeed, stuff in `.gitignore` is ignored. This is [default npm behavior when a `.npmignore` file is missing](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). If you were to publish your package, it would be missing from your release.

Very confusing behavior. Authoring an `.npmignore` file will fix your issue.

**Comment by anodynos** [comment]
Thanks so much for the clarification!
