### ISSUE TITLE
Question: `npm install && install-local file:../../../../../foo` works but foo is at `../../../foo`

### ISSUE THREAD

**Issue by nottoseethesun** [nicojs/node-install-local#20]
I have a scenario where:

```bash
npm install && install-local file:../../../../../foo
```
does work, but `foo` is actually located at `../../../foo` (only three subdirectories up, not five as in the example above).  Verified such that `ls ../../../foo` works (lists the file, `foo`).

I am just wondering what could be going on here.

**Comment by nicojs** [comment]
Hi @nottoseethesun 👋 

This is strange indeed. It might have to do with `file:`. It should not be needed. Could you try `npx install-local ../../../foo`?

**Comment by nottoseethesun** [comment]
That cleared a lot up: On Ubuntu 18.x, `install-local ../../../foo` worked just fine.   It's good to be rid of the trigger for the odd behavior.

As a side note, the uri format (`file://` with the extra dots) worked fine on macOS, but produced a bunch of warnings on Ubuntu 14.x that actually masked a failure to actually install `foo`.
