### ISSUE TITLE
Does not recurse?

### ISSUE THREAD

**Issue by leaanthony** [nicojs/node-install-local#21]
Thanks for this cool utility!

I have a dependency graph as so: Package A -> Package B -> Package C 
All packages define their localDependencies. Installing local Package A installs local Package B but Package B pulls Package C from npm. 

I confirmed this by logging the npm commands. Is there an easy way to make this work?
Thanks.

**Comment by nicojs** [comment]
Recursive trees is not what it is designed for. You could try the following:

You _could_ solve this by adding a `install-local` step in the  `postinstall` script for Package B, however then it will ALWAYS do this, also if someone installs Package B from NPM.

**Comment by leaanthony** [comment]
Thanks for replying @nicojs. Honestly I think pnpm solves a lot of what i want to do. Good luck 👍
