### ISSUE TITLE
Add possibility to ignore package-lock.json

### ISSUE THREAD

**Issue by seanstern** [nicojs/node-install-local#23]
At present, I'm using your package as part of my build process with a package-lock.json file. 

Because the LocalInstaller executes the following command (c.f. [line 99 of Local Installer](https://github.com/nicojs/node-install-local/blob/master/src/LocalInstaller.ts#L99))
```TYPESCRIPT
exec(`npm install --no save ${toInstall}`)
```
this means that any use of LocalInstaller will install *BOTH* any listed local dependencies *AND* packages listed in package-lock.json. For my purposes, this creates incredibly slow builds (e.g. I would like to ignore devDependencies in staging environments, but install-local installs all my devDependencies). 

Would it be possible to create an option or pass a flag such that the LocalInstaller can execute an install *and ignore package-lock.json*? That is, if there were an option such that LocalInstaller could execute
```TYPESCRIPT
exec(`npm install --no save --no-package-lock ${toInstall}`)
```
in certain contexts, that would be really helpful.

I've [forked your package](https://github.com/seanstern/node-install-local-only) to solve this problem in the short term, but if it's possible to incorporate this into this project, I'd be grateful. I can also submit a PR if you can let me know what the preferred default behavior for your project should be.

**Comment by nicojs** [comment]
Installing dependencies other than "localDependencies" was a side effect from the introduction of `package-lock.json` files. This behavior was unfortunate and never the intention. 

Thanks a ton for bringing this to my attention!
