### ISSUE TITLE
Prevent locally installed packages being removed on npm install

### ISSUE THREAD

**Issue by grit96** [nicojs/node-install-local#6]
Any packages installed with install-local are removed when running npm install (or npm install package), requiring me to run install-local again after every npm install. Is there any way to prevent this from happening, or to create a hook to run install-local after npm install?

**Comment by nicojs** [comment]
Yes, this is the default behavior as of npm > 5. I don't like it either. The way i work around it a.t.m. is by defining `install-local` as a `postinstall` step in my package.json. Of course, that only works if you're not planning on shipping that package to `npm`. 

An example can be found here: https://github.com/stryker-mutator/stryker/blob/master/integrationTest/package.json#L30

**Comment by nicojs** [comment]
> Is there any way to prevent this from happening

Not that I know of. 

> or to create a hook to run install-local after npm install?

Only if you create the hook yourself. Any work done by install-local can be unexpected or unwanted in some use cases. I hope you can work around this limitation using my comment above.

**Comment by grit96** [comment]
Thanks @nicojs!
